Salvador/e-commerce-MVC/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CartNamespace.Controllers
{

    public class CartController : Controller
    {

        [Route("/cart")]
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

    }

}

Salvador/e-commerce-MVC/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopNamespace.Controllers
{

    public class ShopController : Controller
    {

        [Route("shop")]
        public IActionResult Index()
        {
            return View();
        }

    }

}

Salvador/e-commerce-MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityManager.Models.ApplicationUser> SignInManager
@inject UserManager<IdentityManager.Models.ApplicationUser> UserManager
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/CSS/style.css">
    <link rel="icon" href="~/images/logo.png" type="image/png">
    <base href="~/">
</head>
<body>

    <nav id="top_bar">

        <div class="top_bar_div">
            <a asp-controller="Home" asp-action="Index" id="logo_container" class="logo_link">
                <img src="~/images/logo.png" alt="Logo" id="logo" />
                <img src="~/images/attention.png" alt="Attention" id="attention" />
            </a>
        </div>

        @{

        if(Convert.ToString(ViewContext.RouteData.Values["controller"]) != "Account"
            || Convert.ToString(ViewContext.RouteData.Values["action"]) == "AccountSite"
            && Convert.ToString(ViewContext.RouteData.Values["controller"]) == "Account")
        {

        <div class="top_bar_div" id="input_top_bar_div">

            <!--Hardcoded part, chance for MySQL query of current product categories-->
            <form action="#">
                <select name="Product category" id="lang">
                <option value="racket">Racket</option>
                <option value="bags">Bags</option>
                <option value="clothes">Clothes</option>
                <option value="shoes">Shoes</option>
                <option value="accessories">Accesories</option>
                <option value="gear">Gear</option>
                <option value="balls">Balls</option>
                </select>
            </form>
            <input type="text" placeholder="Search in e-commerce" id="search" autocomplete="off">  
            <button id="go_button">Go</button>
            
        </div>

        <partial name="_NavBarPartialView"></partial>

        }
        else
        {
            <div id="sign_in_page_sizer"></div>
            <partial name="_LoginPartialView"></partial>

        }

        }

    </nav> 

    <main role="main" class="container" id="MainBodyContainer">
        @RenderBody() <!-- Insert Specific Content of Each View -->
    </main>

    <footer id="footer_index">
        <p>Padel e-commerce property of Aspire Systems ©<br>
            Developer: Salvador Castro Reynoso | 2025
        </p>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

Salvador/e-commerce-MVC/Views/Shared/_LoginPartialView.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityManager.Models.ApplicationUser> SignInManager
@inject UserManager<IdentityManager.Models.ApplicationUser> UserManager

    @{
        if(SignInManager.IsSignedIn(User))
        {


            <div id="partial_view_top_bar_div" class="top_bar_div">
                <ul id="top_bar_ul_partial_view">
                    <li class="top_bar_li_partial_view">
                        <a asp-controller="Account" asp-action="FullRegister" class="navbara" id="navbara_partial_view">Account</a> @*@UserManager.GetUserName(User)*@
                    </li>
                </ul>
            </div>  

        }
        else
        {
            if(Convert.ToString(ViewContext.RouteData.Values["controller"]) == "Account"
            && Convert.ToString(ViewContext.RouteData.Values["action"]) == "SignIn")
            {
                <div id="partial_view_top_bar_div" class="top_bar_div">
                    <ul id="top_bar_ul_partial_view">
                        <li class="top_bar_li_partial_view">
                            <a asp-controller="Account" asp-action="FullRegister" class="navbara" id="navbara_partial_view">Register</a>
                        </li>
                    </ul>
                </div>  
            }
            else if(Convert.ToString(ViewContext.RouteData.Values["controller"]) == "Account"
            && Convert.ToString(ViewContext.RouteData.Values["action"]) == "FullRegister"
            || Convert.ToString(ViewContext.RouteData.Values["controller"]) == "Account"
            && Convert.ToString(ViewContext.RouteData.Values["Action"]) == "ForgotPassword")
            {
                <div id="partial_view_top_bar_div" class="top_bar_div">
                    <ul id="top_bar_ul_partial_view">
                        <li class="top_bar_li_partial_view">
                            <a asp-controller="Account" asp-action="SignIn" class="navbara" id="navbara_partial_view">Sign In</a>
                        </li>
                    </ul>
                </div>  
            }
        }
    }

Salvador/e-commerce-MVC/Views/Shared/_NavBarPartialView.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityManager.Models.ApplicationUser> SignInManager
@inject UserManager<IdentityManager.Models.ApplicationUser> UserManager

    @{

            <div class="top_bar_div">
                <ul id="top_bar_ul">
                    <li class="top_bar_li" id="home_nav_btn">
                        <a asp-controller="Home" asp-action="Index" class="navbara">Home</a>
                    </li>
                    <li class="top_bar_li" id="shop_nav_btn">
                        <a asp-controller="Shop" asp-action="Index" class="navbara">Shop</a>
                    </li>
                    <li class="top_bar_li" id="cart_nav_btn">   
                        <a asp-controller="Cart" asp-action="Index" class="navbara">Cart</a>
                    </li>
                    @{
                        if(SignInManager.IsSignedIn(User)){
                            <li class="top_bar_li" id="sign_in_nav_btn">
                                <a asp-controller="Account" asp-action="AccountSite" class="navbara">Account</a>
                            </li>
                        }
                        else{
                            <li class="top_bar_li" id="sign_in_nav_btn">
                                <a asp-controller="Account" asp-action="SignIn" class="navbara">Sign In</a>
                            </li>
                        }
                    }
                </ul>
            </div>  

    }